### ISSUE TITLE
request help about AutoSeg 3.0.1

### ISSUE THREAD

**Issue by HouqiXie** [NIRALUser/AutoSeg#1] opened 2014-11-05 01:13 UTC
I have reading papers about multi-atlas segmentation of MRI. And I tried to use this soft. But I couldn't got the complete BatchMake scripts after running with AutoSeg GUI. The pipelie runs only to the step of # 14. Multi-Atlas Segmentation. the last lines of the csripts end up as the following picture.
![image](https://cloud.githubusercontent.com/assets/9561985/4910902/c8d1e172-6485-11e4-8afc-069660eb8efd.png)
I have tried namy times in my centOS 6.5 X86_84. Running ImageStat command in AutoSeg with error that says not having libitkalgorithms.so.3. There havn't RPM package for this kind of system in the internet for download. Is it makes the BatchMake scripts didn't complete?

There still an error happens in ABC command. I failed to locate this error in the script, thus  I didn't know where to correct it in the script. 

![image2](https://cloud.githubusercontent.com/assets/9561985/4910905/d55f2274-6485-11e4-9bcd-df24564d4294.png)

Above are problem I meet last days. Anyone have meet the same problems as me? Ciluld anyone tell me hou to solve it!
Thank you in  advance!

Best wishes,
houqi

**Comment by styner** [comment] 2014-11-05 21:07
No worries on the error message from ABC. ABC always writes out "an error" message if there is no prior affine registration and then goes on to compute that missing affine registration (even if the affine registration part is disabled through the ABC protocol settings).

**Comment by styner** [comment] 2014-11-05 21:09
RE ImageStat: you will have to compute ImageStat for your system in order for it work: 
The github is here (for niral utilities, select ImageStat only when you compile it)
https://github.com/NIRALUser/niral_utilities/tree/master

**Comment by styner** [comment] 2014-11-05 21:12
Not sure what the issue is with the BatchMake script which is not fully written out. Does AutoSeg exit/seg-fault while writing this file (which is why you are trying to run it yourself via BatchMake rather than through AutoSeg)? Or is this the file written and tried to be executed by AutoSeg?

**Comment by HouqiXie** [comment] 2014-11-06 01:57
Re styner:
Thanks very much for your reply.
Yes, you said it. AutoSeg writing the script with error, so I can only via BatchMake to run it. The error is core dumped. This error occurs sometimes when I am setting parameters in the GUI and AutoSeg shutting down itself. Whether it is cause by the path of my AutoSeg files and related data?

**Comment by styner** [comment] 2014-11-06 03:22
mm, it is probably an issue with your settings/parameters. Can you copy/paste the content of the computation and parameter file in this thread, so I can take a look?

**Comment by fbudin69500** [comment] 2015-03-18 19:39
No detail given about the error. Closing this thread.

**Closed as completed by fbudin69500** 2015-03-18 19:39 UTC
